#ifndef __SIM_CONFIG__
#define __SIM_CONFIG__
#include "sim_main.h"

#define MAX_TIME_SIM 20
#define HALF_CLK_CYCLE 2
#define ENABLE_CLK_INPUT 0
#define CLK_PIN_NAME clk

#define VERILATOR_MAIN_LOOP()          \
    VERILATOR_SWITCH_INPUT_TO(a, 0); \
    VERILATOR_STEP_AND_EVAL_UNTIL(5); \
    VERILATOR_SWITCH_INPUT_TO(a, 1); \
    VERILATOR_STEP_AND_EVAL_UNTIL(10); \
    VERILATOR_SWITCH_INPUT_TO(a, 0); \
    VERILATOR_STEP_AND_EVAL_UNTIL(15); \
    VERILATOR_SWITCH_INPUT_TO(a, 1); \
    VERILATOR_STEP_AND_EVAL_UNTIL(MAX_TIME_SIM)

#endif
